# Light-Scan Framework - Network Security Scanning Framework
# Copyright (C) 2026 Adam Boulaaz
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

"""
Linux family signature with kernel version fingerprinting.
Combines TCP/IP stack characteristics with banner detection for accurate
kernel and distribution identification.
"""

from .base import OSSignature, VersionRule

LINUX = OSSignature(
    name="Linux",
    family="linux",
    common_orders=[
        ['MSS', 'SAckOK', 'Timestamp', 'WScale'],
        ['MSS', 'SAckOK', 'Timestamp', 'NOP', 'WScale'],
        ['MSS', 'WScale', 'SAckOK', 'Timestamp'],
        ['MSS', 'NOP', 'WScale', 'NOP', 'NOP', 'SAckOK', 'Timestamp'],
        ['MSS', 'Timestamp', 'SAckOK', 'WScale'],
        ['MSS', 'SAckOK', 'Timestamp', 'NOP', 'NOP', 'WScale'],
        ['MSS', 'NOP', 'SAckOK', 'Timestamp', 'WScale'],
        ['MSS', 'NOP', 'NOP', 'SAckOK', 'Timestamp', 'WScale'],
        ['MSS', 'SAckOK', 'Timestamp', 'WScale', 'NOP', 'NOP'],
    ],
    windows=[5720, 29200, 65535, 64240, 32120, 65160, 14600, 5840, 8192],
    ttl_range=(60, 64),
    hlim_range=(60, 64),
    wscale_values=[7, 8, 9, 10, 13, 14],
    mss_values=[1380, 1460, 1440, 8960],
    timestamp_high=True,
    icmp_default_ttl=64,
    udp_closed_port_quirk="icmp_ttl_64_quoted_payload",
    banner_keywords=[
        ("openssh", 10),
        ("gws", 20),
        ("apache", 15),
        ("nginx", 15),
        ("vsftpd", 15),
        ("proftpd", 15),
        ("pure-ftpd", 15),
        ("ubuntu", 20),
        ("debian", 20),
        ("centos", 20),
        ("red hat", 18),
        ("fedora", 18),
        ("dnsmasq", 5),
        ("almalinux", 20),
        ("rocky", 20),
        ("arch", 15),
        ("gentoo", 15),
        ("suse", 15),
        ("opensuse", 15),
        ("raspbian", 20),
        ("alpine", 15),
        ("raspberry pi", 15),
        ("kali", 20),
        ("parrot", 18),
        ("oracle linux", 18),
        ("cloudlinux", 15),
    ],
    service_keywords=[
        ("ssh", 15),
        ("http", 10),
    ],
    exclusive_banner_keywords=[
        "ubuntu", "debian", "centos", "red hat", "fedora",
        "almalinux", "rocky", "arch", "gentoo", "suse",
        "raspbian", "alpine", "kali"
    ],
    version_rules=[

        VersionRule("Linux Kernel 6.12 (LTS 2024+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'WScale', 'SAckOK', 'Timestamp']),
        VersionRule("Linux Kernel 6.6 (LTS 2023+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'WScale']),
        VersionRule("Linux Kernel 6.1 (LTS 2022+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'NOP', 'WScale', 'NOP', 'NOP', 'SAckOK', 'Timestamp']),
        VersionRule("Linux Kernel 6.0-6.5",
                   ttl=64, wscale=14, mss=1460, window=64240,
                   option_order=['MSS', 'WScale', 'SAckOK', 'Timestamp']),
        VersionRule("Linux Kernel 6.x (generic)",
                   ttl=64, wscale=13, mss=1460, window=65535),

        VersionRule("Linux Kernel 5.15 (LTS 2021+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'WScale', 'NOP', 'NOP']),
        VersionRule("Linux Kernel 5.10 (LTS 2020+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'Timestamp', 'SAckOK', 'WScale']),
        VersionRule("Linux Kernel 5.4 (LTS 2019+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'NOP', 'WScale']),
        VersionRule("Linux Kernel 5.0-5.3",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'NOP', 'WScale', 'SAckOK', 'Timestamp']),
        VersionRule("Linux Kernel 5.8+",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'WScale']),
        VersionRule("Linux Kernel 5.x (generic)",
                   ttl=64, wscale=13, mss=1460, window=65535),

        VersionRule("Linux Kernel 4.19 (LTS 2018+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'NOP', 'NOP', 'WScale']),
        VersionRule("Linux Kernel 4.14 (LTS 2017+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'NOP', 'SAckOK', 'Timestamp', 'WScale']),
        VersionRule("Linux Kernel 4.9 (LTS 2016+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'WScale']),
        VersionRule("Linux Kernel 4.4 (LTS 2016)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'Timestamp', 'SAckOK', 'WScale']),
        VersionRule("Linux Kernel 4.0-4.3",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'NOP', 'NOP', 'SAckOK', 'Timestamp', 'WScale']),
        VersionRule("Linux Kernel 4.15+",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'NOP', 'WScale']),
        VersionRule("Linux Kernel 4.18",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'NOP', 'WScale', 'SAckOK', 'Timestamp']),

        VersionRule("Linux Kernel 3.18 (LTS 2014+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'WScale']),
        VersionRule("Linux Kernel 3.16",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'Timestamp', 'SAckOK', 'WScale']),
        VersionRule("Linux Kernel 3.13",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'NOP', 'SAckOK', 'Timestamp', 'WScale']),
        VersionRule("Linux Kernel 3.10 (LTS 2013+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'WScale', 'SAckOK', 'Timestamp']),
        VersionRule("Linux Kernel 3.0-3.9",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'NOP', 'WScale']),
        VersionRule("Linux Kernel 3.12",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'NOP', 'WScale', 'SAckOK', 'Timestamp']),

        VersionRule("Linux Kernel 2.6.39 (2011)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'NOP', 'NOP', 'SAckOK', 'Timestamp', 'WScale']),
        VersionRule("Linux Kernel 2.6.35 (2010)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'NOP', 'WScale']),
        VersionRule("Linux Kernel 2.6.32 (LTS 2009+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'Timestamp', 'SAckOK', 'WScale']),
        VersionRule("Linux Kernel 2.6.31 (2009)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'NOP', 'SAckOK', 'Timestamp', 'WScale']),
        VersionRule("Linux Kernel 2.6.28 (2008)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'WScale', 'SAckOK', 'Timestamp']),
        VersionRule("Linux Kernel 2.6.24 (2008)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'NOP', 'WScale', 'NOP', 'NOP', 'SAckOK', 'Timestamp']),
        VersionRule("Linux Kernel 2.6.18 (2006)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'NOP', 'NOP', 'WScale']),
        VersionRule("Linux Kernel 2.6.16 (2006)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'NOP', 'NOP', 'SAckOK', 'Timestamp', 'WScale']),
        VersionRule("Linux Kernel 2.6.12 (2005)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'Timestamp', 'SAckOK', 'WScale']),
        VersionRule("Linux Kernel 2.6.8 (2004)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'WScale']),
        VersionRule("Linux Kernel 2.6.x (generic, < 2.6.30)",
                   ttl=64, wscale=13, mss=1460, window=65535),


        VersionRule("Ubuntu 24.04 LTS (Noble Numbat) - Kernel 6.8+",
                   banner_contains="ubuntu 24.04"),
        VersionRule("Ubuntu 24.04 (kernel 6.8+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'WScale', 'SAckOK', 'Timestamp']),
        VersionRule("Ubuntu 22.04 LTS (Jammy Jellyfish) - Kernel 5.15+",
                   banner_contains="ubuntu 22.04"),
        VersionRule("Ubuntu 22.04 (kernel 5.15+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'WScale', 'NOP', 'NOP']),
        VersionRule("Ubuntu 20.04 LTS (Focal Fossa) - Kernel 5.4+",
                   banner_contains="ubuntu 20.04"),
        VersionRule("Ubuntu 20.04 (kernel 5.4+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'NOP', 'WScale']),
        VersionRule("Ubuntu 18.04 LTS (Bionic Beaver) - Kernel 4.15+",
                   banner_contains="ubuntu 18.04"),
        VersionRule("Ubuntu 18.04 (kernel 4.15+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'NOP', 'WScale']),
        VersionRule("Ubuntu 16.04 LTS (Xenial Xerus) - Kernel 4.4+",
                   banner_contains="ubuntu 16.04"),
        VersionRule("Ubuntu 16.04 (kernel 4.4+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'Timestamp', 'SAckOK', 'WScale']),
        VersionRule("Ubuntu 14.04 LTS (Trusty Tahr) - Kernel 3.13+",
                   banner_contains="ubuntu 14.04"),
        VersionRule("Ubuntu 14.04 (kernel 3.13+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'NOP', 'SAckOK', 'Timestamp', 'WScale']),
        VersionRule("Ubuntu (from banner)", banner_contains="ubuntu"),

        VersionRule("Debian 12 (Bookworm) - Kernel 6.1+",
                   banner_contains="debian 12"),
        VersionRule("Debian 12 (kernel 6.1+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'NOP', 'WScale', 'NOP', 'NOP', 'SAckOK', 'Timestamp']),
        VersionRule("Debian 11 (Bullseye) - Kernel 5.10+",
                   banner_contains="debian 11"),
        VersionRule("Debian 11 (kernel 5.10+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'Timestamp', 'SAckOK', 'WScale']),
        VersionRule("Debian 10 (Buster) - Kernel 4.19+",
                   banner_contains="debian 10"),
        VersionRule("Debian 10 (kernel 4.19+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'NOP', 'NOP', 'WScale']),
        VersionRule("Debian 9 (Stretch) - Kernel 4.9+",
                   banner_contains="debian 9"),
        VersionRule("Debian 9 (kernel 4.9+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'WScale']),
        VersionRule("Debian 8 (Jessie) - Kernel 3.16+",
                   banner_contains="debian 8"),
        VersionRule("Debian 8 (kernel 3.16+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'Timestamp', 'SAckOK', 'WScale']),
        VersionRule("Debian 7 (Wheezy) - Kernel 3.2+",
                   banner_contains="debian 7"),
        VersionRule("Debian (from banner)", banner_contains="debian"),

        VersionRule("RHEL 9 / CentOS Stream 9 / AlmaLinux 9 / Rocky 9 - Kernel 5.14+",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'WScale', 'NOP', 'NOP']),
        VersionRule("RHEL 8 / CentOS 8 / AlmaLinux 8 / Rocky 8 - Kernel 4.18+",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'NOP', 'WScale', 'SAckOK', 'Timestamp']),
        VersionRule("RHEL 7 / CentOS 7 - Kernel 3.10+",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'WScale', 'SAckOK', 'Timestamp']),
        VersionRule("RHEL 6 / CentOS 6 - Kernel 2.6.32+",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'Timestamp', 'SAckOK', 'WScale']),
        VersionRule("RHEL 5 / CentOS 5 - Kernel 2.6.18+",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'NOP', 'NOP', 'WScale']),
        VersionRule("CentOS (from banner)", banner_contains="centos"),
        VersionRule("Red Hat Enterprise Linux (from banner)", banner_contains="red hat"),
        VersionRule("AlmaLinux (from banner)", banner_contains="almalinux"),
        VersionRule("Rocky Linux (from banner)", banner_contains="rocky"),

        VersionRule("Fedora 40 - Kernel 6.8+",
                   ttl=64, wscale=14, mss=1460, window=64240,
                   option_order=['MSS', 'WScale', 'SAckOK', 'Timestamp']),
        VersionRule("Fedora 38-39 - Kernel 6.2-6.5",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'WScale']),
        VersionRule("Fedora (from banner)", banner_contains="fedora"),

        VersionRule("openSUSE Leap 15.5 - Kernel 5.14+",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'WScale']),
        VersionRule("SUSE Linux Enterprise 15 - Kernel 5.14+",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'NOP', 'WScale', 'SAckOK', 'Timestamp']),
        VersionRule("SUSE (from banner)", banner_contains="suse"),

        VersionRule("Arch Linux (rolling) - Kernel 6.x",
                   ttl=64, wscale=14, mss=1460, window=64240,
                   option_order=['MSS', 'Timestamp', 'SAckOK', 'WScale']),
        VersionRule("Arch Linux (from banner)", banner_contains="archlinux"),

        VersionRule("Alpine Linux - Kernel 5.x/6.x (musl libc)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'WScale', 'SAckOK', 'Timestamp']),
        VersionRule("Alpine Linux (from banner)", banner_contains="alpine"),

        VersionRule("Kali Linux (rolling) - Kernel 6.x",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'WScale']),
        VersionRule("Kali Linux (from banner)", banner_contains="kali"),

        VersionRule("Gentoo Linux - Kernel 5.x/6.x",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'WScale']),
        VersionRule("Gentoo (from banner)", banner_contains="gentoo"),

        VersionRule("Google Cloud Platform (GCP) - Container-Optimized OS",
                   rdns_server="googleapis.com"),
        VersionRule("Google Cloud Platform (GCP) - COS kernel 5.x+",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'WScale', 'SAckOK', 'Timestamp']),
        VersionRule("Google Custom Linux Platforms (Google DNS)",
                   banner_contains="dns.google"),
        VersionRule("Google Custom Linux Platforms (from rdns)",
                   rdns_server="1e100.net"),
        VersionRule("Google Custom Linux Platforms (from banner)",
                   banner_contains="gws"),

        VersionRule("AWS EC2 - Amazon Linux 2023 (kernel 6.1+)",
                   rdns_server="amazonaws.com"),
        VersionRule("AWS EC2 - Amazon Linux 2 (kernel 4.14+/5.10+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'WScale']),
        VersionRule("AWS EC2 - Amazon Linux (kernel 4.9+)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'Timestamp', 'SAckOK', 'WScale']),
        VersionRule("Amazon Linux (from banner)", banner_contains="amazon linux"),
        VersionRule("Amazon Linux (from banner)", banner_contains="amazonlinux"),
        VersionRule("Amazon Web Services (AWS)", banner_contains="cloudfront"),
        VersionRule("Amazon Web Services (AWS)", banner_contains="aws"),
        VersionRule("Amazon Web Services (AWS)", banner_contains="x-amz-rid"),

        VersionRule("DigitalOcean - Ubuntu/Debian (kernel 5.x+)",
                   rdns_server="digitalocean.com"),
        VersionRule("DigitalOcean (from banner)", banner_contains="digitalocean"),

        VersionRule("Azure Linux VM - Ubuntu/CentOS/RHEL",
                   rdns_server="cloudapp.azure.com"),
        VersionRule("Azure Linux VM", rdns_server="azure.com"),

        VersionRule("CloudFlare Services", banner_contains="cloudflare"),
        VersionRule("CloudFlare Services", rdns_server="cloudflare.com"),

        VersionRule("Pantheon Web Services", banner_contains="pantheon"),

        VersionRule("Raspberry Pi OS (Raspbian) - Kernel 6.x",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'WScale']),
        VersionRule("Raspberry Pi OS (from banner)", banner_contains="raspbian"),
        VersionRule("Raspberry Pi (from banner)", banner_contains="raspberry pi"),
        VersionRule("OpenWrt - Kernel 4.x/5.x (small window)",
                   ttl=64, wscale=13, mss=1460, window=5840,
                   option_order=['MSS', 'WScale', 'SAckOK', 'Timestamp']),

        VersionRule("Docker Container (Linux) - kernel 5.x/6.x",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'WScale']),
        VersionRule("Kubernetes Pod (Linux)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'NOP', 'WScale', 'NOP', 'NOP', 'SAckOK', 'Timestamp']),

        VersionRule("Linux w/ OpenSSH 9.9 (latest - kernel 6.x)",
                   banner_contains="openssh_9.9"),
        VersionRule("Linux w/ OpenSSH 9.8 (kernel 6.6+)",
                   banner_contains="openssh_9.8"),
        VersionRule("Linux w/ OpenSSH 9.7 (kernel 6.5+)",
                   banner_contains="openssh_9.7"),
        VersionRule("Linux w/ OpenSSH 9.6 (kernel 6.4+)",
                   banner_contains="openssh_9.6"),
        VersionRule("Linux w/ OpenSSH 9.5 (kernel 6.3+)",
                   banner_contains="openssh_9.5"),
        VersionRule("Linux w/ OpenSSH 9.4 (kernel 6.2+)",
                   banner_contains="openssh_9.4"),
        VersionRule("Linux w/ OpenSSH 9.3 (kernel 6.1+)",
                   banner_contains="openssh_9.3"),
        VersionRule("Linux w/ OpenSSH 9.2 (kernel 6.0+)",
                   banner_contains="openssh_9.2"),
        VersionRule("Linux w/ OpenSSH 9.1 (kernel 5.15+)",
                   banner_contains="openssh_9.1"),
        VersionRule("Linux w/ OpenSSH 9.0 (kernel 5.15+)",
                   banner_contains="openssh_9.0"),
        VersionRule("Linux w/ OpenSSH 9.x (kernel 5.x/6.x era)",
                   banner_contains="openssh_9"),
        VersionRule("Linux w/ OpenSSH 8.9 (kernel 5.10+)",
                   banner_contains="openssh_8.9"),
        VersionRule("Linux w/ OpenSSH 8.8 (kernel 5.10+)",
                   banner_contains="openssh_8.8"),
        VersionRule("Linux w/ OpenSSH 8.7 (kernel 5.10+)",
                   banner_contains="openssh_8.7"),
        VersionRule("Linux w/ OpenSSH 8.6 (kernel 5.9+)",
                   banner_contains="openssh_8.6"),
        VersionRule("Linux w/ OpenSSH 8.5 (kernel 5.8+)",
                   banner_contains="openssh_8.5"),
        VersionRule("Linux w/ OpenSSH 8.4 (kernel 5.7+)",
                   banner_contains="openssh_8.4"),
        VersionRule("Linux w/ OpenSSH 8.3 (kernel 5.6+)",
                   banner_contains="openssh_8.3"),
        VersionRule("Linux w/ OpenSSH 8.2 (kernel 5.5+)",
                   banner_contains="openssh_8.2"),
        VersionRule("Linux w/ OpenSSH 8.1 (kernel 5.4+)",
                   banner_contains="openssh_8.1"),
        VersionRule("Linux w/ OpenSSH 8.0 (kernel 5.3+)",
                   banner_contains="openssh_8.0"),
        VersionRule("Linux w/ OpenSSH 8.x (kernel 4.x/5.x era)",
                   banner_contains="openssh_8"),
        VersionRule("Linux w/ OpenSSH 7.9 (kernel 4.19+)",
                   banner_contains="openssh_7.9"),
        VersionRule("Linux w/ OpenSSH 7.8 (kernel 4.18+)",
                   banner_contains="openssh_7.8"),
        VersionRule("Linux w/ OpenSSH 7.7 (kernel 4.17+)",
                   banner_contains="openssh_7.7"),
        VersionRule("Linux w/ OpenSSH 7.6 (kernel 4.15+)",
                   banner_contains="openssh_7.6"),
        VersionRule("Linux w/ OpenSSH 7.5 (kernel 4.14+)",
                   banner_contains="openssh_7.5"),
        VersionRule("Linux w/ OpenSSH 7.4 (kernel 4.13+)",
                   banner_contains="openssh_7.4"),
        VersionRule("Linux w/ OpenSSH 7.3 (kernel 4.12+)",
                   banner_contains="openssh_7.3"),
        VersionRule("Linux w/ OpenSSH 7.2 (kernel 4.11+)",
                   banner_contains="openssh_7.2"),
        VersionRule("Linux w/ OpenSSH 7.1 (kernel 4.10+)",
                   banner_contains="openssh_7.1"),
        VersionRule("Linux w/ OpenSSH 7.0 (kernel 4.9+)",
                   banner_contains="openssh_7.0"),
        VersionRule("Linux w/ OpenSSH 7.x (kernel 3.x/4.x era)",
                   banner_contains="openssh_7"),
        VersionRule("Linux w/ OpenSSH 6.9 (kernel 4.8+)",
                   banner_contains="openssh_6.9"),
        VersionRule("Linux w/ OpenSSH 6.8 (kernel 4.7+)",
                   banner_contains="openssh_6.8"),
        VersionRule("Linux w/ OpenSSH 6.7 (kernel 4.6+)",
                   banner_contains="openssh_6.7"),
        VersionRule("Linux w/ OpenSSH 6.6 (kernel 4.5+)",
                   banner_contains="openssh_6.6"),
        VersionRule("Linux w/ OpenSSH 6.5 (kernel 4.4+)",
                   banner_contains="openssh_6.5"),
        VersionRule("Linux w/ OpenSSH 6.4 (kernel 4.3+)",
                   banner_contains="openssh_6.4"),
        VersionRule("Linux w/ OpenSSH 6.3 (kernel 4.2+)",
                   banner_contains="openssh_6.3"),
        VersionRule("Linux w/ OpenSSH 6.2 (kernel 4.1+)",
                   banner_contains="openssh_6.2"),
        VersionRule("Linux w/ OpenSSH 6.1 (kernel 4.0+)",
                   banner_contains="openssh_6.1"),
        VersionRule("Linux w/ OpenSSH 6.0 (kernel 3.16+)",
                   banner_contains="openssh_6.0"),
        VersionRule("Linux w/ OpenSSH 6.x (older, kernel 2.6.x/3.x era)",
                   banner_contains="openssh_6"),
        VersionRule("Linux w/ OpenSSH 5.x (very old, kernel 2.6.x era)",
                   banner_contains="openssh_5"),
        VersionRule("Linux w/ OpenSSH 4.x (ancient, kernel 2.4.x/2.6.x)",
                   banner_contains="openssh_4"),

        VersionRule("Linux (modern, kernel 5.x/6.x)",
                   ttl=64, wscale=13, mss=1460, window=65535),
        VersionRule("Linux (kernel 4.x)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'SAckOK', 'Timestamp', 'WScale']),
        VersionRule("Linux (kernel 3.x)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'WScale', 'SAckOK', 'Timestamp']),
        VersionRule("Linux (kernel 2.6.x)",
                   ttl=64, wscale=13, mss=1460, window=65535,
                   option_order=['MSS', 'Timestamp', 'SAckOK', 'WScale']),
        VersionRule("Linux (TTL=64, WScale=7, smaller MSS=1380)",
                   ttl=64, wscale=7, mss=1380, window=65535,
                   option_order=['MSS', 'WScale', 'SAckOK', 'Timestamp']),
        VersionRule("Linux (TTL=64, WScale=14, MSS=1460)",
                   ttl=64, wscale=14, mss=1460, window=64240,
                   option_order=['MSS', 'WScale', 'SAckOK', 'Timestamp']),
    ],
)

SIGNATURES = [LINUX]