# Light-Scan Framework - Network Security Scanning Framework
# Copyright (C) 2026 Adam Boulaaz
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

[SCRIPTS]
# here you can add custom lsse scripts like this ;
# your_script_name = {rargs: t|port=1, script-path: path} ;
# arguments should be separeted by '|' and uses args that are available in this dict ;
# param_map = {
#            'ports': sp,
#            'redirect': redirect,
#            'domain': domain,
#            'dns': dns-server,
#            'wordlist': wordlist,
#            'url': url,
#            'max_pages': max_pages,
#            'max_depth': max_depth,
#            'extensions': extensions,
#            'status_codes': status_codes,
#            't': starget,
#            'user': user,
#            'password': password,
#            'userlist': userlist,
#            'passwordlist': passwordlist,
#            'file': file,
#            'req': req,
#            'ssl': ssl
#        }
# ports should use -> for values and 1 or 0 after it means that the script uses just one port ;
# and any other value considered as multiple ports ;
# Examle -> mamy = {args: t|ports->1,script-path: LSSE.scripts.safe.analysis.dns.mamy}

[VARS]
# if your script uses -sp argument then add it sscripts list but if not ;
# then add it to dscripts list so Lightscan can know were to parse scripts ports or not ;
dscripts = ['dns-subdomain-fuzzing', 'dhcp-discover', 'http-past-pages', 'dns-zone-transfer', 'whois-domain', 'dns-ns', 'spider', 'script', 'http-dir', 'dns-lookup', 'http-cookie', 'http-comments']
sscripts = ['eternalblue','firewall-detect', 'ssh-brute', 'ssh-auth-methods', 'http-request', 'http-cert', 'http-headers', 'http-methods', 'http-robots', 'http-title','ssh-info']