# Light-Scan Framework - Network Security Scanning Framework
# Copyright (C) 2026 Adam Boulaaz
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

[BUILT-IN]
# if you add a speed preset in built in then dont expect it to work ;
# because you will need manually to add to confparser.py Global.buitin list ;
# but even after that it's not gonna work untill adding that preset in Lightscan.py speed_presets dict ;

paranoid = {threads:2,timeout:4.5}
slow = {threads: 30, timeout: 3.3}
normal = {threads: 60, timeout: 2.8}
fast = {threads: 120, timeout: 2.8}
insane = {threads: 240, timeout: 1.5}
light-mode = {threads: 400, timeout: 1.5}

[CUSTOM]
# here you can add custom speed presets like this ;
# your_preset_name = {threads: (int64) threads_number, timeout: (float64) timeout_number} ;
# put in mind that more then 400 threads is more then what Lightscan is capable of ;